sudo: false
language: python
env:
  - PYTHON_VERSION=3.5
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
install:
  # q2-dummy-types is only required for the dummy methods and
  # visualizers provided as examples. Remove this dependency when you're
  # ready to develop your plugin, and add your own dependencies (if there are
  # any).
  - conda create --yes -n test-env -c qiime2 python=$PYTHON_VERSION qiime nose flake8
  - source activate test-env
  - pip install .
script:
  - nosetests
  - flake8 q2_vsearch setup.py
